version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rss-reader
      MYSQL_USER: rss-reader
      MYSQL_PASSWORD: rss-reader
volumes:
  db_data: {}